# SPDX-FileCopyrightText: 2026 Sebastien Rousseau <sebastian.rousseau@gmail.com>
# SPDX-License-Identifier: Apache-2.0 OR MIT

AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
