AllCops:
  TargetRubyVersion: 3.3
  NewCops: enable
  Exclude:
    - 'vendor/**/*'
    - 'db/schema.rb'

Layout/LineLength:
  Max: 100

Style/Documentation:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: true
